# Generated by Django 4.2.5 on 2023-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_rename_amount_rate_value_rate_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='title',
            new_name='black_market',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='value',
        ),
        migrations.AddField(
            model_name='rate',
            name='black_market_sell',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
