# Generated by Django 4.2.5 on 2023-09-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rename_title_rate_black_market_remove_rate_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='black_market_sell',
            new_name='black_market_buy',
        ),
    ]
